import 'dart:typed_data';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:nervix_app/Features/Home_view/data/models/user_model.dart';

class PdfReportGenerator {
  static Future<Uint8List> _buildPdfBytes(UserModel user) async {
    final pdf = pw.Document();

    final uid = FirebaseAuth.instance.currentUser?.uid ?? '';
    final List<QueryDocumentSnapshot<Map<String, dynamic>>> historyDocs;
    if (uid.isEmpty) {
      historyDocs = [];
    } else {
      final snap = await FirebaseFirestore.instance
          .collection('users')
          .doc(uid)
          .collection('history')
          .limit(10)
          .get();
      historyDocs = snap.docs;
    }

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Header(
              level: 0,
              child: pw.Text(
                'Nervix Medical Report',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Text(
              'Patient Information:',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.Divider(),
            pw.Bullet(text: 'Name: ${user.name}'),
            pw.Bullet(text: 'Age: ${user.age}'),
            pw.Bullet(text: 'Gender: ${user.gender}'),
            pw.Bullet(text: 'Condition: ${user.condition}'),
            pw.Bullet(text: 'Contact: ${user.phone}'),
            pw.SizedBox(height: 30),
            pw.Text(
              'Recent Abnormal Neural Events:',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.Divider(),
            if (historyDocs.isEmpty)
              pw.Text('No abnormal events recorded.')
            else
              pw.Column(
                children: historyDocs.map((doc) {
                  final data = doc.data();
                  final ts = data['timestamp'] as Timestamp?;
                  return pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(ts?.toDate().toString() ?? 'N/A'),
                      pw.Text('Signal: ${data['signalValue']}'),
                    ],
                  );
                }).toList(),
              ),
            pw.SizedBox(height: 50),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Text('Generated by Nervix AI Dashboard'),
            ),
          ],
        ),
      ),
    );

    return pdf.save();
  }

  static Future<void> generateAndPrintReport(UserModel user) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => _buildPdfBytes(user),
    );
  }

  static Future<void> shareReport(UserModel user) async {
    final bytes = await _buildPdfBytes(user);
    final stamp = DateTime.now().toIso8601String().replaceAll(':', '-');
    await Printing.sharePdf(
      bytes: bytes,
      filename: 'nervix_report_$stamp.pdf',
    );
  }
}
