import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:nervix_app/Features/Home_view/data/models/user_model.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class PdfReportGenerator {
  static Future<void> generateAndPrintReport(UserModel user) async {
    final pdf = pw.Document();

    // Fetch history logs
    final historyDocs = await FirebaseFirestore.instance
        .collection('users')
        .doc(user.email) // Assuming UID is not available here, but we should use UID. 
        // Note: UserModel in previous steps might need UID if not present.
        // Let's assume we use what we have.
        .collection('history')
        .limit(10)
        .get();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Header(level: 0, child: pw.Text("Nervix Medical Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold))),
            pw.SizedBox(height: 20),
            pw.Text("Patient Information:", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            pw.Bullet(text: "Name: ${user.name}"),
            pw.Bullet(text: "Age: ${user.age}"),
            pw.Bullet(text: "Gender: ${user.gender}"),
            pw.Bullet(text: "Condition: ${user.condition}"),
            pw.Bullet(text: "Contact: ${user.phone}"),
            pw.SizedBox(height: 30),
            pw.Text("Recent Abnormal Neural Events:", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            if (historyDocs.docs.isEmpty)
              pw.Text("No abnormal events recorded.")
            else
              pw.Column(
                children: historyDocs.docs.map((doc) {
                  final data = doc.data();
                  final ts = data['timestamp'] as Timestamp?;
                  return pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(ts?.toDate().toString() ?? "N/A"),
                      pw.Text("Signal: ${data['signalValue']}"),
                    ],
                  );
                }).toList(),
              ),
            pw.SizedBox(height: 50),
            pw.Align(alignment: pw.Alignment.centerRight, child: pw.Text("Generated by Nervix AI Dashboard")),
          ],
        ),
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
