// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9M8yURCXYsJn_XFqWIqIADUE2yoMBTyU',
    appId: '1:491101938301:web:e2a925d24f6a65afa2c714',
    messagingSenderId: '491101938301',
    projectId: 'nervix-10d98',
    authDomain: 'nervix-10d98.firebaseapp.com',
    databaseURL: 'https://nervix-10d98-default-rtdb.firebaseio.com',
    storageBucket: 'nervix-10d98.firebasestorage.app',
    measurementId: 'G-GC3KDBYC2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQcLVbJKzKZ_vQ7kvcJyzw8yUdRBMix7A',
    appId: '1:491101938301:android:eefdbc6d5715b8c7a2c714',
    messagingSenderId: '491101938301',
    projectId: 'nervix-10d98',
    databaseURL: 'https://nervix-10d98-default-rtdb.firebaseio.com',
    storageBucket: 'nervix-10d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgvzjbt4fmr4HTRzapJOpInL_v0DMlLlU',
    appId: '1:491101938301:ios:963b51498b0eee5fa2c714',
    messagingSenderId: '491101938301',
    projectId: 'nervix-10d98',
    databaseURL: 'https://nervix-10d98-default-rtdb.firebaseio.com',
    storageBucket: 'nervix-10d98.firebasestorage.app',
    iosBundleId: 'ai.medical.nervixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgvzjbt4fmr4HTRzapJOpInL_v0DMlLlU',
    appId: '1:491101938301:ios:2548142b20ecaca7a2c714',
    messagingSenderId: '491101938301',
    projectId: 'nervix-10d98',
    databaseURL: 'https://nervix-10d98-default-rtdb.firebaseio.com',
    storageBucket: 'nervix-10d98.firebasestorage.app',
    iosBundleId: 'com.example.nervixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9M8yURCXYsJn_XFqWIqIADUE2yoMBTyU',
    appId: '1:491101938301:web:50176cac0ccb9ec9a2c714',
    messagingSenderId: '491101938301',
    projectId: 'nervix-10d98',
    authDomain: 'nervix-10d98.firebaseapp.com',
    databaseURL: 'https://nervix-10d98-default-rtdb.firebaseio.com',
    storageBucket: 'nervix-10d98.firebasestorage.app',
    measurementId: 'G-PY4NEZZVWX',
  );
}
