// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOoOdWoRtjhiVVYh7yXb6w2DRhfPqTLc0',
    appId: '1:571849249430:web:a244ecac14c1704cb228b7',
    messagingSenderId: '571849249430',
    projectId: 'nuro-af526',
    authDomain: 'nuro-af526.firebaseapp.com',
    databaseURL: 'https://nuro-af526-default-rtdb.firebaseio.com',
    storageBucket: 'nuro-af526.firebasestorage.app',
    measurementId: 'G-LG9W4MM8QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBf9LBPCZDd94rX6sCkQ50RJOvd0Pl7Y',
    appId: '1:571849249430:android:c88c10b546ed33b8b228b7',
    messagingSenderId: '571849249430',
    projectId: 'nuro-af526',
    databaseURL: 'https://nuro-af526-default-rtdb.firebaseio.com',
    storageBucket: 'nuro-af526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsBoBMAJjo0SUhwqNEgLbMiupZEoIk3k',
    appId: '1:571849249430:ios:c32ead5dbc5472d9b228b7',
    messagingSenderId: '571849249430',
    projectId: 'nuro-af526',
    databaseURL: 'https://nuro-af526-default-rtdb.firebaseio.com',
    storageBucket: 'nuro-af526.firebasestorage.app',
    iosBundleId: 'com.example.neuroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEsBoBMAJjo0SUhwqNEgLbMiupZEoIk3k',
    appId: '1:571849249430:ios:c32ead5dbc5472d9b228b7',
    messagingSenderId: '571849249430',
    projectId: 'nuro-af526',
    databaseURL: 'https://nuro-af526-default-rtdb.firebaseio.com',
    storageBucket: 'nuro-af526.firebasestorage.app',
    iosBundleId: 'com.example.neuroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOoOdWoRtjhiVVYh7yXb6w2DRhfPqTLc0',
    appId: '1:571849249430:web:c65135de6cd85fbfb228b7',
    messagingSenderId: '571849249430',
    projectId: 'nuro-af526',
    authDomain: 'nuro-af526.firebaseapp.com',
    databaseURL: 'https://nuro-af526-default-rtdb.firebaseio.com',
    storageBucket: 'nuro-af526.firebasestorage.app',
    measurementId: 'G-001YD0X5X2',
  );
}
