import 'package:flutter/material.dart';
import 'package:nervix_app/Core/localization/translation_extension.dart';

class AppLegalContent {
  static List<String> getPrivacySections(BuildContext context) {
    if (context.isArabic) {
      return [
        'نيرفيكس ("نحن"، "نا") يحترم خصوصيتك. توضح هذه السياسة كيفية تعاملنا مع المعلومات عند استخدام تطبيقنا للهاتف المحمول.',
        'المعلومات التي نجمعها: بيانات الحساب التي تقدمها (مثل البريد الإلكتروني والاسم والحقول المتعلقة بالصحة التي تختار إدخالها)، واستخدام التطبيق، والبيانات الناتجة عن ميزات المراقبة المتصلة عند تهيئتها (على سبيل المثال، قراءات الإشارة المخزنة أو المعروضة في التطبيق).',
        'كيف نستخدم المعلومات: لتوفير الوظائف الأساسية للتطبيق، وتخصيص تجربتك، والحفاظ على الأمن، وتحسين الموثوقية. نحن لا نبيع معلوماتك الصحية الشخصية.',
        'تخزين البيانات: قد يتم معالجة البيانات باستخدام خدمات مثل Firebase (المصادقة، وFirestore، وقاعدة البيانات في الوقت الفعلي) ضمن تكوين مشروع Firebase الخاص بك. أنت مسؤول عن تأمين مشروع Firebase الخاص بك والامتثال للقوانين المعمول بها.',
        'حقوقك: بناءً على اختصاصك القضائي، قد يكون لديك حقوق في الوصول إلى البيانات الشخصية أو تصحيحها أو حذفها. يمكنك تحديث معلومات الملف الشخصي في التطبيق حيثما كان ذلك متاحاً.',
        'الأطفال: هذا التطبيق غير مخصص للاستخدام من قبل الأفراد الذين لا يمكنهم الموافقة قانونياً. إذا كنت تعتقد أننا جمعنا بيانات من قاصر بشكل غير صحيح، فاتصل بنا.',
        'التغييرات: قد نقوم بتحديث هذه السياسة؛ سيتم عكس التغييرات الجوهرية في التطبيق عندما يكون ذلك ممكناً عملياً.',
        'الاتصال: استخدم خيارات الاتصال داخل التطبيق للأسئلة المتعلقة بالخصوصية المتعلقة بهذا التطبيق.',
      ];
    }
    return [
      'Nervix ("we", "our", or "us") respects your privacy. This policy describes how we handle information when you use our mobile application.',
      'Information We Collect: account data you provide (such as email, name, and health-related profile fields you choose to enter), usage of the app, and data generated by connected monitoring features when configured (for example, signal readings stored or displayed in the app).',
      'How We Use Information: to provide core app functionality, personalize your experience, maintain security, and improve reliability. We do not sell your personal health information.',
      'Data Storage: data may be processed using services such as Firebase (Authentication, Firestore, Realtime Database) under your Firebase project configuration. You are responsible for securing your Firebase project and compliance with applicable laws.',
      'Your Rights: depending on your jurisdiction, you may have rights to access, correct, or delete personal data. You can update profile information in the app where available.',
      'Children: this app is not intended for use by individuals who cannot lawfully consent. If you believe we have collected data from a minor improperly, contact us.',
      'Changes: we may update this policy; material changes will be reflected in the app when reasonably practical.',
      'Contact: use the in-app contact options for privacy-related questions related to this application.',
    ];
  }

  static List<String> getTermsSections(BuildContext context) {
    if (context.isArabic) {
      return [
        'باستخدام نيرفيكس، فإنك توافق على هذه الشروط. إذا كنت لا توافق، فلا تستخدم التطبيق.',
        'ليست نصيحة طبية: نيرفيكس هو أداة دعم ومراقبة. ليس بديلاً عن النصائح الطبية المهنية أو التشخيص أو العلاج. اطلب دائماً مشورة مقدمي الرعاية الصحية المؤهلين فيما يتعلق بالحالات الطبية.',
        'الطوارئ: التطبيق ليس بديلاً عن خدمات الطوارئ. في حالات الطوارئ، اتصل برقم الطوارئ المحلي (على سبيل المثال 112 أو 911 أو 999) أو استخدم قنوات الطوارئ المناسبة.',
        'بلا ضمانات: يتم توفير التطبيق "كما هو" دون ضمانات من أي نوع. نحن لا نضمن التشغيل السلس أو الخالي من الأخطاء أو الدقيق تماماً للتنبيهات أو القراءات.',
        'تحديد المسؤولية: إلى أقصى حد يسمح به القانون، نحن لسنا مسؤولين عن أي أضرار غير مباشرة أو عرضية أو تبعية تنشأ عن استخدام التطبيق.',
        'أمن الحساب: أنت مسؤول عن حماية أوراق اعتمادك وجهازك. قم بإخطار الأطراف المناسبة إذا كنت تشك في وصول غير مصرح به.',
        'التغييرات: قد نقوم بتعديل هذه الشروط؛ الاستمرار في الاستخدام بعد التغييرات يعتبر قبولاً حيثما يسمح القانون بذلك.',
      ];
    }
    return [
      'By using Nervix, you agree to these terms. If you do not agree, do not use the application.',
      'Not Medical Advice: Nervix is a support and monitoring tool. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of qualified health providers regarding medical conditions.',
      'Emergency: the app is not a replacement for emergency services. In an emergency, call your local emergency number (for example 112, 911, or 999) or use appropriate emergency channels.',
      'No Warranty: the app is provided "as is" without warranties of any kind. We do not guarantee uninterrupted, error-free, or completely accurate operation of alerts or readings.',
      'Limitation of Liability: to the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from use of the app.',
      'Account Security: you are responsible for safeguarding your credentials and device. Notify appropriate parties if you suspect unauthorized access.',
      'Changes: we may modify these terms; continued use after changes constitutes acceptance where permitted by law.',
    ];
  }
}
