class AppLegalContent {
  static const List<String> privacySections = [
    'Nervix ("we", "our", or "us") respects your privacy. This policy describes how we handle information when you use our mobile application.',
    'Information We Collect: account data you provide (such as email, name, and health-related profile fields you choose to enter), usage of the app, and data generated by connected monitoring features when configured (for example, signal readings stored or displayed in the app).',
    'How We Use Information: to provide core app functionality, personalize your experience, maintain security, and improve reliability. We do not sell your personal health information.',
    'Data Storage: data may be processed using services such as Firebase (Authentication, Firestore, Realtime Database) under your Firebase project configuration. You are responsible for securing your Firebase project and compliance with applicable laws.',
    'Your Rights: depending on your jurisdiction, you may have rights to access, correct, or delete personal data. You can update profile information in the app where available.',
    'Children: this app is not intended for use by individuals who cannot lawfully consent. If you believe we have collected data from a minor improperly, contact us.',
    'Changes: we may update this policy; material changes will be reflected in the app when reasonably practical.',
    'Contact: use the in-app contact options for privacy-related questions related to this application.',
  ];

  static const List<String> termsSections = [
    'By using Nervix, you agree to these terms. If you do not agree, do not use the application.',
    'Not Medical Advice: Nervix is a support and monitoring tool. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of qualified health providers regarding medical conditions.',
    'Emergency: the app is not a replacement for emergency services. In an emergency, call your local emergency number (for example 112, 911, or 999) or use appropriate emergency channels.',
    'No Warranty: the app is provided "as is" without warranties of any kind. We do not guarantee uninterrupted, error-free, or completely accurate operation of alerts or readings.',
    'Limitation of Liability: to the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from use of the app.',
    'Account Security: you are responsible for safeguarding your credentials and device. Notify appropriate parties if you suspect unauthorized access.',
    'Changes: we may modify these terms; continued use after changes constitutes acceptance where permitted by law.',
  ];
}
